# Generated by Django 4.1.3 on 2022-12-29 10:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='usersignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('emailid', models.EmailField(max_length=254)),
                ('uname', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('zip', models.CharField(max_length=20)),
                ('mobile', models.BigIntegerField()),
                ('pwd', models.CharField(max_length=20)),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 29, 16, 5, 14, 47117))),
            ],
        ),
    ]
